/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MOTOR_A.h"
#include "MOTOR_A_aliases.h"
#include "MOTOR_B.h"
#include "MOTOR_B_aliases.h"
#include "MOTOR_C.h"
#include "MOTOR_C_aliases.h"
#include "MOTOR_D.h"
#include "MOTOR_D_aliases.h"
#include "Pin_BackLight.h"
#include "Pin_BackLight_aliases.h"
#include "PWM.h"
#include "Pin_Buzz.h"
#include "Pin_Buzz_aliases.h"
#include "Clock_1.h"
#include "ISR_PWM.h"
#include "BLE_1_gatt.h"
#include "BLE_1.h"
#include "BLE_1_HAL_PVT.h"
#include "BLE_1_STACK_PVT.h"
#include "BLE_1_StackGap.h"
#include "BLE_1_StackGatt.h"
#include "BLE_1_StackGattDb.h"
#include "BLE_1_StackHostMain.h"
#include "BLE_1_StackL2cap.h"
#include "BLE_1_StackGattServer.h"
#include "BLE_1_StackGattClient.h"
#include "BLE_1_Stack.h"
#include "BLE_1_eventHandler.h"
#include "BLE_1_custom.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSD_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_SelfTest.h"
#include "ISR_Finger.h"
#include "Pin_Finger.h"
#include "Pin_Finger_aliases.h"
#include "Pin_G.h"
#include "Pin_G_aliases.h"
#include "Pin_B.h"
#include "Pin_B_aliases.h"
#include "Em_EEPROM.h"
#include "BLE_1_bless_isr.h"
#include "CapSense_ISR.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

